[package]
name = "feedspool"
version = "0.1.0"
description = "A utility for regularly fetching feeds from the web"
authors = ["Les Orchard <me@lmorchard.com>"]
edition = "2018"
repository = "https://github.com/lmorchard/telnet-gateway-menu/"
license = "MIT"
categories = [ "command-line-interface", "command-line-utilities" ]
keywords = [ "telnet", "bbs" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
